export default {
  roots: {
    ac: `尖. 具体含有下列四种意义： （1）尖形→针、刺 （2）烈（尖）味→酸、辣、苦 （3）尖顶→顶上、高 （4）尖锐→敏锐`,
    ag: 'do act 做, 动',
    agri: 'field, 田地, 农田',
    agro: 'field, 田地, 农田',
    agr: 'field, 田地, 农田',
    ann: 'year, 年',
    annu: 'year, 年',
    enn: 'year, 年',
    audi: 'hear, 听',
    audit: 'hear, 听',
    bell: 'war, 战争',
    brev: 'short, 短',
    ced: 'go, 行走',
    ceed: 'go, 行走',
    cess: 'go, 行走',
    cept: 'take, 拿, 取',
    cid: 'cut, kill, 切, 傻 || 降临, 降落',
    cis: 'cut, kill, 切, 傻',
    circ: 'ring, 环, 圆',
    claim: 'cry, shout, 喊, 叫',
    clam: 'cry, shout, 喊, 叫',
    clar: '清楚, 明白',
    clud: 'close, shut, 关闭',
    clus: 'close, shut, 关闭',
    cogn: 'know, 知道',
    cord: 'heart, 心',
    corpor: 'body, 体',
    corp: 'body, 体',
    cred: 'believe, trust 相信, 信任',
    cruc: 'cross, 十字',
    cur: 'care, 关心, 挂念, 注意 || run, 跑',
    curs: 'run, 跑',
    cour: 'run, 跑',
    cours: 'run, 跑',
    dent: 'tooth, 牙齿',
    di: 'day, 日',
    dict: 'say, 言, 说',
    dic: 'say, 言, 说',
    dit: 'give, 给',
    don: 'give, 给',
    'do': 'give, 给',
    du: 'two, 二',
    duc: 'lead, 引导',
    duct: 'lead, 引导',
    ed: 'eat, 吃',
    equ: 'equal, 等, 均, 平',
    ev: 'age, 年龄',
    fact: 'do, make, 做',
    fac: 'do, make, 做',
    fer: 'bring, carry, 带, 拿',
    flor: 'flower, 花',
    flour: 'flower, 花',
    flu: 'flow, 流',
    fus: 'pour, 灌, 流, 倾泻',
    grad: 'step, go, grade, 步, 走, 级',
    gram: 'write, something written or drawn, 写, 画, 文字, 图形',
    graph: 'write, writing, an instrument for making records, 写, 画, 文字, 图形, 记录器',
    gress: 'go, walk 行走',
    habit: 'dwell, 居住',
    hibit: 'hold, 拿, 持',
    hospit: 'guest, 客人',
    idio: 'peculiar, own, private, proper, 特殊的, 个人的, 专有的',
    insul: 'island, 岛',
    it: 'go, 行走',
    ject: 'throw, 投掷',
    juven: 'young, 年轻, 年少',
    lect: 'choose, gather 选, 收',
    leg: 'choose, gather 选, 收 || 读 || 法',
    lig: 'choose, gather 选, 收',
    lev: 'raise, 举, 升',
    liber: 'free, 自由',
    lingu: 'language, 语言',
    liter: 'letter, 文字, 字母',
    loc: 'place, 地方',
    log: 'speak, 言, 说',
    loqu: 'speak, 言, 说',
    lun: 'moon, 月亮',
    man: 'dwell, stay, 居住, 停留 || hand, 手',
    manu: 'hand, 手',
    mar: 'sea, 海',
    med: '治疗, 救治',
    medi: 'middle, 中间',
    memor: 'memory, 记忆',
    merg: 'dip, sink, 沉, 没',
    mers: 'dip, sink, 沉, 没',
    migr: 'remove, move, 迁移',
    milit: 'soldier, 兵',
    mini: 'small, little, 小',
    min: 'small, little, 小 || 伸出, 突出',
    mir: 'wonder, 惊奇, 惊异',
    miss: 'send, 投, 送, 发',
    mit: 'send, 投, 送, 发',
    mob: 'move, 动',
    mort: 'death, 死',
    mot: 'move, 移动, 动',
    nomin: 'name, 名',
    nov: 'new, 新',
    numer: 'number, 数',
    onym: 'name, 名',
    oper: 'work, 工作',
    ori: 'rise, 升起',
    paci: 'peace, 和平, 平静',
    pel: 'push, drive, 推, 驱, 逐',
    pend: 'hang, 悬挂 || weight 称重',
    pens: 'hang, 悬挂 || weight 称重',
    pet: 'seek, 追求',
    phon: 'sound, 声音',
    pict: 'paint, 画, 描绘',
    plen: 'full, 满, 全',
    plic: 'fold, 折, 重叠',
    pon: 'put, 放置',
    popul: 'people, 人民',
    port: 'carry, 拿, 带, 运',
    pos: 'put, 放置',
    preci: 'price 价值',
    punct: 'point, prick, 点, 刺',
    pur: 'pure, 清, 纯, 净',
    rect: 'right, straight, 正, 直',
    rupt: 'break, 破',
    sal: 'salt, 盐',
    scend: 'climb, 爬, 攀',
    scens: 'climb, 爬, 攀',
    sci: 'know, 知',
    sec: 'follow, 跟随',
    sequ: 'follow, 跟随',
    sect: 'cut, 切割',
    sent: 'feel, 感觉',
    sens: 'feel, 感觉',
    sid: 'sit, 坐',
    sist: 'stand, 站立',
    son: 'sound, 声音',
    spec: '看',
    spect: 'look, 看',
    spir: 'breathe, 呼吸',
    tail: 'cut, 切割',
    tain: 'hold, 握, 持, 守',
    ten: 'hold, 握, 持, 守',
    tin: 'hold, 握, 持, 守',
    tect: 'cover, 掩盖',
    tele: 'far, 远',
    tempor: 'time, 时',
    tend: 'stretch, 伸',
    tens: 'stretch, 伸',
    tent: 'stretch, 伸',
    terr: 'earch, land, 土地, 陆地',
    text: 'weave, 编织',
    tract: 'draw, 拉, 抽, 引',
    un: 'one, 一',
    uni: 'one, 一',
    urb: 'city, 城市',
    vac: 'empty, 空',
    vacu: 'empty, 空',
    vad: 'walk, go, 行走',
    vas: 'walk, go, 行走',
    vari: 'change, 变',
    ven: 'come, 来',
    vert: 'turn, 转',
    vers: 'turn, 转',
    vi: 'way, 路',
    via: 'way, 路',
    vis: 'see, 看',
    vid: 'see, 看',
    vit: 'life, 生命',
    viv: 'live, 活',
    aer: '空气, 空中, 航空',
    aero: '空气, 空中, 航空',
    alt: '高',
    am: '爱',
    ambul: '行, 走',
    anim: '生命',
    anthrop: '人, 人类',
    anthropo: '人, 人类',
    aqu: '水',
    arch: '统治者, 首脑',
    archy: '统治',
    avi: '鸟',
    bat: '打',
    biblio: '书',
    brig: '战斗, 打',
    cas: '下降',
    cad: '下降',
    cert: '确实, 确信',
    chron: '时',
    clin: '倾',
    cosm: '宇宙, 世界',
    cosmo: '宇宙, 世界',
    cracy: '统治',
    crat: '支持/实行...统治的人',
    cub: '躺, 卧',
    cult: '耕, 培养',
    cycl: '圆, 环, 轮',
    cyclo: '圆, 环, 轮',
    dem: '人民',
    demo: '人民',
    dexter: '右',
    doc: '教',
    dom: '屋, 家',
    dorm: '睡眠',
    drom: '跑',
    ego: '我',
    err: '漫游, 走, 形',
    fabl: '言',
    fabul: '言',
    feder: '联盟',
    ferv: '沸, 热',
    fict: '塑造, 虚构',
    fig: '塑造, 虚构',
    fid: '信任',
    fil: '线',
    flat: '吹',
    flect: '弯曲',
    flex: '弯曲',
    flict: '打击',
    frag: '破, 折',
    fract: '破, 折',
    frig: '冷',
    fug: '逃, 散',
    fund: '底, 基础',
    found: '底, 基础',
    gam: '婚姻',
    gran: '谷物, 谷粒',
    grav: '重',
    greg: '群, 集合',
    gyn: '妇女',
    gynec: '妇女',
    gyneco: '妇女',
    hal: '呼吸',
    helic: '螺旋',
    helico: '螺旋',
    hes: '粘着',
    her: '粘着',
    ign: '火',
    integr: '整, 全',
    junct: '连接, 连结',
    later: '边',
    let: '小，微小',
    legis: '法',
    luc: '光',
    lumin: '光',
    magn: '大',
    magni: '大',
    matr: '母',
    matri: '母',
    metro: '母',
    mega: '大',
    mens: '测量',
    ment: '心, 神, 智, 思, 意',
    misc: '混合, 混杂',
    mis: '恨, 厌恶',
    miso: '恨, 厌恶',
    mon: '告诫, 提醒 || 单独, 一个',
    mur: '墙',
    mut: '变换',
    nat: '诞生',
    nav: '船',
    nect: '结, 系',
    nex: '结, 系',
    negr: '黑',
    nigr: '黑',
    nihil: '无',
    noc: '伤害',
    nox: '伤害',
    noct: '夜',
    nocti: '夜',
    norm: '规范, 正规, 正常',
    nutri: '营养',
    orn: '装饰',
    par: '生, 产',
    parl: '说, 谈',
    past: '喂, 食, 面团',
    path: '疾病, 疗法',
    patho: '疾病, 疗法',
    pathy: '疾病, 疗法',
    patr: '父, 祖',
    patri: '父, 祖',
    ped: '脚, 足 || 儿童, 小孩',
    petr: '石',
    petro: '石',
    phag: '吃',
    phil: '爱',
    philo: '爱',
    phob: '怕',
    phobia: '怕',
    plex: '重叠, 叠',
    polis: '城市',
    prim: '第一, 最初',
    radic: '根',
    ras: '刮, 擦',
    rad: '刮, 擦',
    rid: '笑',
    ris: '笑',
    rod: '咬, 啮',
    ros: '咬, 啮',
    rot: '轮, 转',
    rud: '原始, 粗鲁',
    rur: '农村',
    rus: '农村',
    sat: '足, 满, 饱',
    satis: '足, 满, 饱',
    satur: '足, 满, 饱',
    sen: '老',
    simil: '相似, 相同',
    simul: '相似, 相同',
    sol: '单独 || 太阳',
    soph: '智慧',
    sper: '希望',
    spers: '散, 撒',
    spars: '散, 撒',
    stitute: 'set up, place,: 建立, 放置',
    stitut: 'set up, place,: 建立, 放置',
    splend: '发光, 照耀',
    etell: '星',
    tact: '触',
    tag: '触',
    the: '神',
    theo: '神',
    ton: '音',
    tort: '扭',
    tour: '迂回, 转',
    trud: '推, 冲',
    trus: '推, 冲',
    tut: '监护, 看管',
    tuit: '监护, 看管',
    umbr: '阴影',
    ut: '用',
    us: '用',
    vag: '走, 漫游',
    val: '强',
    van: '空, 无',
    ver: '真实',
    veri: '真实',
    voo: '声音, 叫喊',
    vok: '声音, 叫喊',
    vol: '意志, 意愿',
    volunt: '意志, 意愿',
    volu: '滚, 转',
    volv: '滚, 转'
  },
  prefixes: {
    a: '无, 不, 非 || 含有in, on, at, by, with, to, of等意义 || 加强意义',
    ab: '离去, 相反, 不',
    ac: '含有at, to之意 || 表示加强及引申意义',
    ad: '含有at, to之意 || 表示加强意义',
    af: '含有at, to之意 || 表示加强意义',
    ag: '含有at, to之意 || 表示加强意义',
    amphi: '两, 双',
    an: '无, 不 || 加强或引申意义',
    ante: '前, 先',
    anti: '反对, 相对, 防止',
    ap: '加强或引申意义 || 离开',
    apo: '离开',
    ar: '含有at, to之意 || 表示加强及引申意义',
    as: '含有at, to之意 || 表示加强及引申意义',
    at: '含有at, to之意 || 表示加强及引申意义',
    auto: '自己, 自动',
    be: '使..., 使成为... || 加以..., 饰以..., 用...做某事 || 在 || 加强或引申意义',
    bene: '善, 好',
    bi: '两, 二',
    by: '旁, 侧, 非正式的, 副',
    circum: '周围, 环绕',
    co: '共同',
    col: '共同',
    com: '共同 || 加强或引申意义',
    con: '共同 || 加强或引申意义',
    contra: '反对, 相反, 相对',
    cor: '共同, 相互 || 加强或引申意义',
    counter: '反对, 相对',
    de: '否定, 非, 相反 || 除去, 取消, 毁 || 离开 || 向下, 降低, 减少 || 使成..., 做成... || 表强调',
    deca: '十',
    deci: '十分之一',
    demi: '半',
    di: '双 || 不, 无, 相反 || 取消, 除去, 毁 || 加在含有"分开", "否定"等意义的单词之前, 表示加强意义 || 分开, 离, 散',
    dia: '贯通, 对穿, 透过, 相对',
    dif: '分开, 否定, 不',
    dis: '不, 无, 相反 || 取消, 除去, 毁 || 加在含有"分开", "否定"等意义的单词之前, 表示加强意义 || 分开, 离, 散',
    dys: '不良, 恶, 困难',
    e: '加强或引申意义 || 出, 外 || 除去',
    ef: '出, 离去',
    em: '表示"至于...之内", "上...", || 表示"用...做某事, "饰以..., 配以..." || 表示"使成...状态", "致使...", "使之如...", "作成..."',
    en: '表示"置于...之中", "登上...", "使上..." || 表示"用...做某事, "饰以..., 配以..." || 表示"使成...状态", "致使...", "使之如...", "作成..." || 加在动词前, 表示"in", 或只做加强意义',
    endo: '内',
    ennea: '九',
    ile: '名词后缀',
    eu: '优, 善, 好',
    ex: '出, 外, 由...中弄出 || 前任的, 以前的 || 表示"使...", "做..."或加强意义',
    exo: '外部的',
    per: '完全, 贯穿, 自始至终',
    sym: '共同, 相同',
    re: '往回, 向后 || 再, 重复, 重新',
    pro: '向前'
  },
  postfixes: {
    aceous: 'a. 表示有...性质的, 属于...的, 如...的, 具有...的',
    acious: 'a. 表示多...的, 有...性质的, 属于...的, 具有...的',
    acity: 'n. 构成抽象名词, 表示性质, 状态, 情况. 与形容词后缀-acious相对应',
    acle: 'n. 构成实物名词即抽象名词',
    al: 'a. 表示属于...的, 如...的, 具有...的 || n. 构成抽象名词, 表示行为, 状态, 事情. 表示人或物',
    ance: 'n. 抽象名词',
    ancy: 'n. 抽象名词',
    age: 'n. 表示集合名词, 总称 || 表场所, 地点 || 表示费用 || 表示行为或行为的结果 || 表状态, 情况, 身份或其他 || 表示物',
    ate: 'v. 表示做, 造成, 使之成...',
    ent: 'a. 形容词后缀',
    fy: '使...',
    ity: 'n. 名词后缀',
    ion: 'n',
    logy: 'n. 学科',
    tary: '自己总结, 一般的形容词后缀',
    ry: 'n. 名词'
  }
}
